// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// egyptian_set.js
// drawn from Kate Monk's Onomastikon, (c) 1997 Kate Monk
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// json format
// http://en.wikipedia.org/wiki/JSON
name_set['solar_systems'] = [
    'Eridanus', 'Cassiopeia', 'Scorpius', 'Crux', 'Cancer', 'Leo', 'Canis Major', 'Andromeda', 'Taurus', 'Lyra', 'Virgo', 'Sagittarius', 'Aquarius', 'Cygnus', 'Corvus', 'Ursa Major', 'Cepheus', 'Grus', 'Draco', 'Corona Australis', 'Capricornus', 'Pegasus', 'Perseus', 'Auriga', 'Gemini', 'Columba', 'Bootes', 'Crater', 'Orion', 'Hydra', 'Corona Borealis', 'Pisces', 'Lynx', 'Aquila', 'Serpens', 'Phoenix', 'Lepus', 'Carina', 'Canes Venatici', 'Triangulum Australe', 'Puppis', 'Cetus', 'Aries', 'Libra', 'Ophiuchus', 'Ara', 'Delphinus', 'Coma Berenices', 'Triangulum', 'Piscis Austrinus', 'Canis Minor', 'Centaurus', 'Hydrus', 'Hercules', 'Equuleus', 'Ursa Minor', 'Vulpecula', 'Pavo', 'Octans', 'Leo Minor', 'Vela', 'Sagitta', 'Camelopardalis', 'Uran', 'Coristeror', 'Ceulon', 'Hydri', 'Lesa', 'Lerista', 'Deri', 'Piuous', 'Alderaan', 'Hoth', 'Korriban', 'Cerali', 'Pesal', 'Cesci', 'Cygux', 'Aust', 'Pinistis Ausari', 'Calor', 'Trix Cajoore', 'Anoris', 'Caesar Corinu', 'Conophus Lesce', 'Malus', 'Corus', 'Pibrate', 'Cesanu', 'Camuel Phor', 'Tanis', 'Canscorus', 'Lesch', 'Conusa', 'Belem', 'Miscistag Cati', 'Panx', 'Hailasaurus', 'Peria', 'Concordia', 'Uruban', 'Drinul', 'Trio', 'Alaransta', 'Nike', 'Eris', 'Athena', 'Juno', 'Aleen', 'Akiva', 'Affa', 'Chandel', 'Calcoraan', 'Carnelion', 'Dathomir', 'Durkteel', 'Endor', 'Espirion', 'Florrum', 'Felucia', 'Gallan', 'Gad', 'Haidoral', 'Halcyon', 'Imvur', 'Ison', 'Jelucan', 'Jakku', 'Kadavo', 'Khorm', 'Lanteeb', 'Llanic', 'Mandalore', 'Moraband', 'Naboo', 'Nal Hutta', 'Onderon', 'Orondia', 'Patite Pattuna', 'Plexis', 'Quarzite', 'Quermia', 'Rakata', 'Ryloth', 'Saleucami', 'Stygeon', 'Taris', 'Tatooine', 'Ubardia', 'Umbra', 'Vassek', 'Vetine', 'Wor tandell', 'Whiforla', 'Xiri', 'Xurl', 'Yaga Minor', 'Yavin', 'Zatooine', 'Zolan'
];

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -